#!/usr/bin/env sh

help() {
    echo "pkg help -- work in progress"
    # TODO: Add documentation.
}

info() {
    pacman -Qi "$@"
}

list() {
    shift
    pacman -Q "$@"
}

if [ $# -lt 1 ]; then
    help
    exit 0
fi

case "$1" in
    h|help)
        help
        ;;

    info)
        info "$@"
        ;;

    list)
        list "$@"
        ;;

    *)
        printf "Unknown option: %s\n\n" "$*"
        help
        ;;
esac
