* pkg
A wrapper for various package managers. ~pkg~ is made for those that want a tool
that abstracts all the commonly used commands behind a universal interface.

Heavily inspired by:
+ [[https://github.com/lukrop/xbps-pkg][lukrop/xbps-pkg]]
+ [[https://www.freebsd.org/cgi/man.cgi?query=pkg&apropos=0&sektion=0&manpath=FreeBSD+12.1-RELEASE+and+Ports&arch=default&format=html][FreeBSD's pkg(8)]]

** Installation
As an example, the following steps use a local bin directory.

*** If you want everything
Clone this repository, then make a symbolic link to ~pkg~ on your ~$PATH~.

#+BEGIN_SRC shell
ln -s $HOME/code/pkg/pkg $HOME/.local/bin
#+END_SRC

*** If you only want the tool
Use ~cURL~ to download the tool and save it in your local ~bin~ directory.

#+BEGIN_SRC shell
curl -o $HOME/.local/bin/pkg -L https://github.com/vednoc/pkg/raw/main/pkg
#+END_SRC

*** Make the tool executable
After installation is complete, make ~pkg~ executable (otherwise you'll get
"permission denied" error).

#+BEGIN_SRC shell
chmod +x $HOME/.local/bin/pkg
#+END_SRC

** Usage
Type ~pkg help~ in your terminal emulator to get started.

All available commands will be documented in the help option. Also, check out the
source code to see the implementation of this tool.

** Contributing
Fork this project, clone the repository, install [[https://editorconfig.org/][EditorConfig]] plugin if
necessary, then send over a Pull Request. Keep the changes small and relevant.

** License
Licensed under the [[./license][MIT license]].
